'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AddonOption
    Public Property OptionID As Integer
    Public Property ItemID As Nullable(Of Integer)
    Public Property Size As String
    Public Property Amount As Nullable(Of Decimal)

End Class
