'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Division
    Public Property DivisionID As Integer
    Public Property Distance As Nullable(Of Decimal)
    Public Property Category As String
    Public Property Description As String
    Public Property StartTime As Nullable(Of Date)
    Public Property Price As Nullable(Of Decimal)
    Public Property RaceID As Nullable(Of Integer)

End Class
