'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class EntriesDBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=EntriesDBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property C__MigrationHistory() As DbSet(Of C__MigrationHistory)
    Public Overridable Property AddonItems() As DbSet(Of AddonItem)
    Public Overridable Property AddonOptions() As DbSet(Of AddonOption)
    Public Overridable Property AspNetRoles() As DbSet(Of AspNetRole)
    Public Overridable Property AspNetUserClaims() As DbSet(Of AspNetUserClaim)
    Public Overridable Property AspNetUserLogins() As DbSet(Of AspNetUserLogin)
    Public Overridable Property AspNetUsers() As DbSet(Of AspNetUser)
    Public Overridable Property Divisions() As DbSet(Of Division)
    Public Overridable Property Entries() As DbSet(Of Entry)
    Public Overridable Property Organisers() As DbSet(Of Organiser)
    Public Overridable Property Participants() As DbSet(Of Participant)
    Public Overridable Property PaymentDetails() As DbSet(Of PaymentDetail)
    Public Overridable Property pflogs() As DbSet(Of pflog)
    Public Overridable Property RaceEvents() As DbSet(Of RaceEvent)
    Public Overridable Property Sales() As DbSet(Of Sale)
    Public Overridable Property Substitutions() As DbSet(Of Substitution)
    Public Overridable Property SystemLogs() As DbSet(Of SystemLog)
    Public Overridable Property TypeLookups() As DbSet(Of TypeLookup)

End Class
