'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Entry
    Public Property EntryID As Integer
    Public Property ParticipantID As Nullable(Of Integer)
    Public Property RaceID As Nullable(Of Integer)
    Public Property DivisionID As Nullable(Of Integer)
    Public Property Amount As Nullable(Of Double)
    Public Property Status As String
    Public Property PaymentReference As String
    Public Property DistanceChange As Nullable(Of Boolean)
    Public Property ChangePaymentRef As String
    Public Property TransferID As Nullable(Of Integer)
    Public Property Result As String

End Class
