'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Organiser
    Public Property OrgID As Integer
    Public Property OrgName As String
    Public Property OrgEmail As String
    Public Property OrgTel As String
    Public Property OrgWebsite As String
    Public Property OrgVatNumber As String
    Public Property AdminUserID As Nullable(Of Integer)
    Public Property Image As String

End Class
