'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ParticipantExport
    Public Property ParticipantID As Integer
    Public Property FirstName As String
    Public Property MiddleNames As String
    Public Property LastName As String
    Public Property IDNumber As String
    Public Property DOB As Nullable(Of Date)
    Public Property EmailAddress As String
    Public Property MedicalName As String
    Public Property MedicalNumber As String
    Public Property EmergencyContact As String
    Public Property EmergencyNumber As String
    Public Property BoodType As String
    Public Property Allergies As String
    Public Property AdditionalInfo As String
    Public Property DoctorName As String
    Public Property DoctorContact As String
    Public Property Clubname As String
    Public Property RaceNumber As String
    Public Property Country As String
    Public Property Address As String
    Public Property City As String
    Public Property Province As String
    Public Property EventMailer As Boolean
    Public Property Offers As Boolean

End Class
