'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PaymentDetail
    Public Property PaymentID As Integer
    Public Property OrgID As Nullable(Of Integer)
    Public Property MerchantID As String
    Public Property MerchantKey As String
    Public Property MerchantPassPhrase As String

End Class
