'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RaceEvent
    Public Property RaceID As Integer
    Public Property RaceName As String
    Public Property RaceDescription As String
    Public Property RaceDate As Nullable(Of Date)
    Public Property RaceType As String
    Public Property Coordinates As String
    Public Property Address As String
    Public Property City As String
    Public Property Province As String
    Public Property AdminCharge As Nullable(Of Double)
    Public Property OrgID As Nullable(Of Integer)
    Public Property Image As String
    Public Property Background As String
    Public Property ImgDetail1 As String
    Public Property ImgDetail2 As String
    Public Property ImgDetail3 As String
    Public Property DispClasses As Boolean
    Public Property DispAdmCharge As Boolean
    Public Property DispAddress As Boolean
    Public Property RaceHtmlPage As String
    Public Property Indemnity As String
    Public Property TandC As String
    Public Property EntriesCloseDate As Nullable(Of Date)
    Public Property PF_ToClient As Boolean
    Public Property Admin_ToClient As Boolean
    Public Property Admin_Rate As Decimal

End Class
