'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sale
    Public Property SaleID As Integer
    Public Property RaceID As Nullable(Of Integer)
    Public Property DivisionID As Nullable(Of Integer)
    Public Property ItemID As Nullable(Of Integer)
    Public Property OptionID As Nullable(Of Integer)
    Public Property UserID As String
    Public Property Indemnity As Nullable(Of Boolean)
    Public Property TandC As Nullable(Of Boolean)
    Public Property ParticipantID As Nullable(Of Integer)
    Public Property M_reference As Nullable(Of Integer)
    Public Property Pf_reference As Nullable(Of Integer)
    Public Property Verified As Nullable(Of Boolean)
    Public Property SaleDate As Nullable(Of Date)

End Class
