'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Substitution
    Public Property TransferID As Integer
    Public Property FromParticipantID As Nullable(Of Integer)
    Public Property ToParticipantID As Nullable(Of Integer)
    Public Property Status As String
    Public Property Amount As Nullable(Of Double)
    Public Property PaymentReference As String

End Class
