'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SystemLog
    Public Property LogID As Integer
    Public Property UserID As Nullable(Of Integer)
    Public Property ActionPerformed As String
    Public Property [Date] As Nullable(Of Date)
    Public Property Time As Nullable(Of System.TimeSpan)

End Class
