'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Voucher
    Public Property VoucherID As Integer
    Public Property Code As Nullable(Of Double)
    Public Property Value As Nullable(Of Decimal)
    Public Property IssuedBy As String
    Public Property Pf_Reference As String
    Public Property M_Reference As Nullable(Of Integer)
    Public Property [Date] As Nullable(Of Date)
    Public Property Status As String
    Public Property UsedBy As String
    Public Property UsedDate As Nullable(Of Date)
    Public Property UsedM_Reference As Nullable(Of Integer)

End Class
